# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/cedricleclercq/Documents/School/cg/2. Engine/utils"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/cedricleclercq/Documents/School/cg/2. Engine/utils"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/cedricleclercq/Documents/School/cg/2. Engine/utils/CMakeFiles" "/Users/cedricleclercq/Documents/School/cg/2. Engine/utils//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/cedricleclercq/Documents/School/cg/2. Engine/utils/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

2Dobjects/Line2D.o: 2Dobjects/Line2D.cpp.o

.PHONY : 2Dobjects/Line2D.o

# target to build an object file
2Dobjects/Line2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/2Dobjects/Line2D.cpp.o
.PHONY : 2Dobjects/Line2D.cpp.o

2Dobjects/Line2D.i: 2Dobjects/Line2D.cpp.i

.PHONY : 2Dobjects/Line2D.i

# target to preprocess a source file
2Dobjects/Line2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/2Dobjects/Line2D.cpp.i
.PHONY : 2Dobjects/Line2D.cpp.i

2Dobjects/Line2D.s: 2Dobjects/Line2D.cpp.s

.PHONY : 2Dobjects/Line2D.s

# target to generate assembly for a file
2Dobjects/Line2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/2Dobjects/Line2D.cpp.s
.PHONY : 2Dobjects/Line2D.cpp.s

2Dobjects/Point2D.o: 2Dobjects/Point2D.cpp.o

.PHONY : 2Dobjects/Point2D.o

# target to build an object file
2Dobjects/Point2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/2Dobjects/Point2D.cpp.o
.PHONY : 2Dobjects/Point2D.cpp.o

2Dobjects/Point2D.i: 2Dobjects/Point2D.cpp.i

.PHONY : 2Dobjects/Point2D.i

# target to preprocess a source file
2Dobjects/Point2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/2Dobjects/Point2D.cpp.i
.PHONY : 2Dobjects/Point2D.cpp.i

2Dobjects/Point2D.s: 2Dobjects/Point2D.cpp.s

.PHONY : 2Dobjects/Point2D.s

# target to generate assembly for a file
2Dobjects/Point2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/2Dobjects/Point2D.cpp.s
.PHONY : 2Dobjects/Point2D.cpp.s

3Dobjects/vector3d.o: 3Dobjects/vector3d.cc.o

.PHONY : 3Dobjects/vector3d.o

# target to build an object file
3Dobjects/vector3d.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/3Dobjects/vector3d.cc.o
.PHONY : 3Dobjects/vector3d.cc.o

3Dobjects/vector3d.i: 3Dobjects/vector3d.cc.i

.PHONY : 3Dobjects/vector3d.i

# target to preprocess a source file
3Dobjects/vector3d.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/3Dobjects/vector3d.cc.i
.PHONY : 3Dobjects/vector3d.cc.i

3Dobjects/vector3d.s: 3Dobjects/vector3d.cc.s

.PHONY : 3Dobjects/vector3d.s

# target to generate assembly for a file
3Dobjects/vector3d.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/3Dobjects/vector3d.cc.s
.PHONY : 3Dobjects/vector3d.cc.s

Figure/Face.o: Figure/Face.cpp.o

.PHONY : Figure/Face.o

# target to build an object file
Figure/Face.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Figure/Face.cpp.o
.PHONY : Figure/Face.cpp.o

Figure/Face.i: Figure/Face.cpp.i

.PHONY : Figure/Face.i

# target to preprocess a source file
Figure/Face.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Figure/Face.cpp.i
.PHONY : Figure/Face.cpp.i

Figure/Face.s: Figure/Face.cpp.s

.PHONY : Figure/Face.s

# target to generate assembly for a file
Figure/Face.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Figure/Face.cpp.s
.PHONY : Figure/Face.cpp.s

Utilities/Color.o: Utilities/Color.cpp.o

.PHONY : Utilities/Color.o

# target to build an object file
Utilities/Color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/Color.cpp.o
.PHONY : Utilities/Color.cpp.o

Utilities/Color.i: Utilities/Color.cpp.i

.PHONY : Utilities/Color.i

# target to preprocess a source file
Utilities/Color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/Color.cpp.i
.PHONY : Utilities/Color.cpp.i

Utilities/Color.s: Utilities/Color.cpp.s

.PHONY : Utilities/Color.s

# target to generate assembly for a file
Utilities/Color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/Color.cpp.s
.PHONY : Utilities/Color.cpp.s

Utilities/easy_image.o: Utilities/easy_image.cc.o

.PHONY : Utilities/easy_image.o

# target to build an object file
Utilities/easy_image.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/easy_image.cc.o
.PHONY : Utilities/easy_image.cc.o

Utilities/easy_image.i: Utilities/easy_image.cc.i

.PHONY : Utilities/easy_image.i

# target to preprocess a source file
Utilities/easy_image.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/easy_image.cc.i
.PHONY : Utilities/easy_image.cc.i

Utilities/easy_image.s: Utilities/easy_image.cc.s

.PHONY : Utilities/easy_image.s

# target to generate assembly for a file
Utilities/easy_image.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/easy_image.cc.s
.PHONY : Utilities/easy_image.cc.s

Utilities/ini_configuration.o: Utilities/ini_configuration.cc.o

.PHONY : Utilities/ini_configuration.o

# target to build an object file
Utilities/ini_configuration.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/ini_configuration.cc.o
.PHONY : Utilities/ini_configuration.cc.o

Utilities/ini_configuration.i: Utilities/ini_configuration.cc.i

.PHONY : Utilities/ini_configuration.i

# target to preprocess a source file
Utilities/ini_configuration.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/ini_configuration.cc.i
.PHONY : Utilities/ini_configuration.cc.i

Utilities/ini_configuration.s: Utilities/ini_configuration.cc.s

.PHONY : Utilities/ini_configuration.s

# target to generate assembly for a file
Utilities/ini_configuration.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Utilities/ini_configuration.cc.s
.PHONY : Utilities/ini_configuration.cc.s

engine.o: engine.cc.o

.PHONY : engine.o

# target to build an object file
engine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cc.o
.PHONY : engine.cc.o

engine.i: engine.cc.i

.PHONY : engine.i

# target to preprocess a source file
engine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cc.i
.PHONY : engine.cc.i

engine.s: engine.cc.s

.PHONY : engine.s

# target to generate assembly for a file
engine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/engine.cc.s
.PHONY : engine.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... 2Dobjects/Line2D.o"
	@echo "... 2Dobjects/Line2D.i"
	@echo "... 2Dobjects/Line2D.s"
	@echo "... 2Dobjects/Point2D.o"
	@echo "... 2Dobjects/Point2D.i"
	@echo "... 2Dobjects/Point2D.s"
	@echo "... 3Dobjects/vector3d.o"
	@echo "... 3Dobjects/vector3d.i"
	@echo "... 3Dobjects/vector3d.s"
	@echo "... Figure/Face.o"
	@echo "... Figure/Face.i"
	@echo "... Figure/Face.s"
	@echo "... Utilities/Color.o"
	@echo "... Utilities/Color.i"
	@echo "... Utilities/Color.s"
	@echo "... Utilities/easy_image.o"
	@echo "... Utilities/easy_image.i"
	@echo "... Utilities/easy_image.s"
	@echo "... Utilities/ini_configuration.o"
	@echo "... Utilities/ini_configuration.i"
	@echo "... Utilities/ini_configuration.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

